// packages/examples/vue-example/src/features/users/components/RoleDropdownId.vue
<script setup lang="ts">
import type { Role } from "../types/user-form.types";

const props = defineProps<{
  modelValue: string;
  options: Role[];
  error?: string;
}>();

const emit = defineEmits<{
  "update:modelValue": [value: string];
  blur: [];
}>();

function selectedLabel(): string {
  return props.options.find((r) => r.id === props.modelValue)?.name ?? "Pilih role";
}
</script>

<template>
  <div style="margin-bottom: 1rem;">
    <label style="display: block; margin-bottom: 0.25rem;">Role</label>

    <div
      :style="{
        border: props.error ? '1px solid red' : '1px solid #ccc',
        borderRadius: '4px',
        padding: '0.5rem',
      }"
    >
      <button
        type="button"
        style="background: none; border: none; cursor: pointer; padding: 0;"
        @blur="emit('blur')"
      >
        {{ selectedLabel() }}
      </button>

      <div style="margin-top: 0.5rem; display: flex; gap: 0.5rem;">
        <button
          v-for="role in props.options"
          :key="role.id"
          type="button"
          :style="{
            padding: '0.25rem 0.75rem',
            border: '1px solid #ccc',
            borderRadius: '4px',
            cursor: 'pointer',
            background: props.modelValue === role.id ? '#e0e7ff' : '#fff',
          }"
          @click="emit('update:modelValue', role.id)"
        >
          {{ role.name }}
        </button>
      </div>

      <button
        v-if="props.modelValue"
        type="button"
        style="margin-top: 0.5rem; font-size: 0.75rem; color: red; background: none; border: none; cursor: pointer;"
        @click="emit('update:modelValue', '')"
      >
        Hapus pilihan
      </button>
    </div>

    <p
      v-if="props.error"
      role="alert"
      style="color: red; margin: 0.25rem 0 0; font-size: 0.875rem;"
    >
      {{ props.error }}
    </p>
  </div>
</template>

// packages/examples/react-example/src/features/users/components/role-dropdown-id.tsx
import type { Role } from "../types/user-form.types";

type RoleDropdownIdProps = {
  value: string;
  options: Role[];
  error?: string;
  onChange: (value: string) => void;
  onBlur?: () => void;
};

export function RoleDropdownId({ value, options, error, onChange, onBlur }: RoleDropdownIdProps) {
  const selectedRole = options.find((role) => role.id === value);

  return (
    <div style={{ marginBottom: "1rem" }}>
      <label style={{ display: "block", marginBottom: "0.25rem" }}>Role</label>

      <div
        style={{
          border: error ? "1px solid red" : "1px solid #ccc",
          borderRadius: "4px",
          padding: "0.5rem",
        }}
      >
        <button
          type="button"
          onBlur={onBlur}
          style={{ background: "none", border: "none", cursor: "pointer", padding: 0 }}
        >
          {selectedRole ? selectedRole.name : "Pilih role"}
        </button>

        <div style={{ marginTop: "0.5rem", display: "flex", gap: "0.5rem" }}>
          {options.map((role) => (
            <button
              key={role.id}
              type="button"
              onClick={() => onChange(role.id)}
              style={{
                padding: "0.25rem 0.75rem",
                border: "1px solid #ccc",
                borderRadius: "4px",
                cursor: "pointer",
                background: value === role.id ? "#e0e7ff" : "#fff",
              }}
            >
              {role.name}
            </button>
          ))}
        </div>

        {value ? (
          <button
            type="button"
            onClick={() => onChange("")}
            style={{
              marginTop: "0.5rem",
              fontSize: "0.75rem",
              color: "red",
              background: "none",
              border: "none",
              cursor: "pointer",
            }}
          >
            Hapus pilihan
          </button>
        ) : null}
      </div>

      {error ? (
        <p role="alert" style={{ color: "red", margin: "0.25rem 0 0", fontSize: "0.875rem" }}>
          {error}
        </p>
      ) : null}
    </div>
  );
}
